### ISSUE TITLE
No logs to identify issues - Blocking development

### ISSUE THREAD

**Issue by sramac2** [payu-intrepos/PayUCheckoutPro-Flutter#11]
- I tried to run the example app to test the checkout flow and I am receiving the attached error. There are no logs being printed on the console to see what went wrong. I added my merchant key, added all the URLs, and uncommented the hash function. I assume the API is responding to an unexpected response and the app does not know how to parse it. Any kind of log if added will be straightforward for everyone to fix the issue themselves. Thank you in advance. 

**Update:** I was able to fix it but if you guys add more logs whatever is happening in the background, it will be very beneficial.

**Comment by sidhu-patil** [comment]
Here is a comprehensive guide on how to seamlessly integrate PayU's payment gateway into your Flutter app, which you can explore and benefit from: https://sudhanshupatil.medium.com/integrating-payu-payment-gateway-in-your-flutter-app-c3849433b32e


Use:  Debugger
