### ISSUE TITLE
Facing issue in android, in iOS working fine

### ISSUE THREAD

**Issue by geodrive-ranjeet** [payu-intrepos/PayUCheckoutPro-Flutter#12]
Through Exception when initiate payment.

Compiler allocated 4160KB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
E/AndroidRuntime(13559): FATAL EXCEPTION: main
E/AndroidRuntime(13559): Process:, PID: 13559
E/AndroidRuntime(13559): android.content.res.Resources$NotFoundException: Resource ID #0x0
E/AndroidRuntime(13559):        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:226)
E/AndroidRuntime(13559):        at android.content.res.Resources.getValue(Resources.java:1437)
E/AndroidRuntime(13559):        at androidx.appcompat.widget.ResourceManagerInternal.createDrawableIfNeeded(ResourceManagerInternal.java:180)
E/AndroidRuntime(13559):        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:145)
E/AndroidRuntime(13559):        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:136)
E/AndroidRuntime(13559):        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:66)
E/AndroidRuntime(13559):        at com.payu.ui.viewmodel.h.b(SourceFile:15)
E/AndroidRuntime(13559):        at com.payu.ui.viewmodel.h.onQuickOptionsFetched(SourceFile:1)
E/AndroidRuntime(13559):        at com.payu.checkoutpro.layers.PayUbizApiLayer.showQuickOption(SourceFile:2)
E/AndroidRuntime(13559):        at com.payu.checkoutpro.models.m.onCheckoutDetailsResponse(SourceFile:114)
E/AndroidRuntime(13559):        at com.payu.india.Tasks.GetPaymentInstrumentTask.onPostExecute(GetPaymentInstrumentTask.java:461)
E/AndroidRuntime(13559):        at com.payu.india.Tasks.GetPaymentInstrumentTask.onPostExecute(GetPaymentInstrumentTask.java:63)
E/AndroidRuntime(13559):        at android.os.AsyncTask.finish(AsyncTask.java:771)
E/AndroidRuntime(13559):        at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
E/AndroidRuntime(13559):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
E/AndroidRuntime(13559):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13559):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(13559):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(13559):        at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(13559):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13559):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(13559):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by itsAkshatG13** [comment]
Facing the same error in Android ... any resolution ?

**Comment by geodrive-ranjeet** [comment]
> Facing the same error in Android ... any resolution ?

save app logo in drawable folder and also save same image(logo) in iOS asset and after this pass logo image name in PayUCheckoutProConfigKeys.merchantLogo property in payUCheckoutProConfig

**Comment by itsAkshatG13** [comment]
Hey @geodrive-ranjeet can you please explain in details .. I have the application icon for both ios and android already in my project. So should I create a new folder for the drawables. Can you please help me out with the steps or screenshots.

**Comment by geodrive-ranjeet** [comment]
> Hey @geodrive-ranjeet can you please explain in details .. I have the application icon for both ios and android already in my project. So should I create a new folder for the drawables. Can you please help me out with the steps or screenshots.

Check below screenshots for details.

![Screenshot 2023-06-06 at 5 46 37 PM](https://github.com/payu-intrepos/PayUCheckoutPro-Flutter/assets/135410664/c9f61a12-05ec-47b3-b869-c95176cd5f31)
![Screenshot 2023-06-06 at 5 46 56 PM](https://github.com/payu-intrepos/PayUCheckoutPro-Flutter/assets/135410664/2a3019cd-5bb3-4f9e-8982-3b28f9a77e4b)
![Screenshot 2023-06-06 at 5 49 14 PM](https://github.com/payu-intrepos/PayUCheckoutPro-Flutter/assets/135410664/8e5dfb85-df6d-4bda-86ee-1ac15f26a1f0)

**Comment by itsAkshatG13** [comment]
Thanks a lot @geodrive-ranjeet can you also let me know how to automatically navigate back the user once the payment is failed or success ? I am able to do the payment but user is stuck on the message screen saying success or failure not navigating back.

**Comment by geodrive-ranjeet** [comment]
> Thanks a lot @geodrive-ranjeet can you also let me know how to automatically navigate back the user once the payment is failed or success ? I am able to do the payment but user is stuck on the message screen saying success or failure not navigating back.

Just implements  with PayUCheckoutProProtocol in controller or state widget
and override onPaymentSuccess,onPaymentFailure methods

**Comment by itsAkshatG13** [comment]
I am using the methods to navigate to a different page in my app but the methods are either not calling or calling after a very long time... is there a time response for the succcess or failure tasks to get executed @geodrive-ranjeet
