### ISSUE TITLE
Facing issue in android, loads infinite or restarts the app

### ISSUE THREAD

**Issue by itsAkshatG13** [payu-intrepos/PayUCheckoutPro-Flutter#13]
I recently started facing an issue with the way payu package works. I am just trying to use the .openCheckoutScreen method which opens up the payment screen. When the app is freshly installed I am able to do 3-4 payments successfully however after that the payu payment gateway shows infinite loading or after successful payment it restarts my app. No callback is received in these cases in failure/cancel/success. 
Here is my flutter doctor and a piece of code I am trying to implement.
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!`

Code implemented: 
`    try {
      _checkoutPro.openCheckoutScreen(
          payUPaymentParams: payUPaymentParams,
          payUCheckoutProConfig: payUConfigParams);
    } catch (e) {
      print('exception_payment $e');
    }`

**Comment by itsAkshatG13** [comment]
Using the stable v1.0.0 which does not cause this issue.

**Comment by sidhu-patil** [comment]
Here is a comprehensive guide on how to seamlessly integrate PayU's payment gateway into your Flutter app, which you can explore and benefit from: https://sudhanshupatil.medium.com/integrating-payu-payment-gateway-in-your-flutter-app-c3849433b32e

**Comment by shahfaizalc** [comment]
kindly use the latest version https://pub.dev/packages/payu_checkoutpro_flutter

**Comment by bashu-riyan** [comment]
solution for this please im already using latest version.
