### ISSUE TITLE
How to resolve error `type '_Map<dynamic, dynamic>' is not a subtype of type 'String' of 'value'`

### ISSUE THREAD

**Issue by kirankumbhar** [payu-intrepos/PayUCheckoutPro-Flutter#14]
I'm trying to integrate payu payment gateway using test credentials. But I'm getting following error upon calling `openCheckoutScreen()`

type '_Map<dynamic, dynamic>' is not a subtype of type 'String' of 'value'

There are no logs so not able to trace the origin of the error.

**Comment by shahfaizalc** [comment]
kindly use the latest version https://pub.dev/packages/payu_checkoutpro_flutter
