### ISSUE TITLE
Dart Version update

### ISSUE THREAD

**Issue by Valath** [payu-intrepos/PayUCheckoutPro-Flutter#17]
Version restriction should be updated to 1.3.1.4 to support the latest Dart version

**Comment by ShubhGar** [comment]
@Valath we will check and update you.

**Comment by shahfaizalc** [comment]
@Valath we will check and update you soon

**Comment by Valath** [comment]
Team, updates please

**Comment by ShubhGar** [comment]
@Valath  we are working on same and will release updated version next week.

**Comment by shahfaizalc** [comment]
kindly use 1.1.3 version of your flutter we have updated dart version to below 
  sdk: ">=2.17.5 <=3.3.3"
