### ISSUE TITLE
Violation of Google Play Policies: `minkasu` sdk

### ISSUE THREAD

**Issue by albinpk** [payu-intrepos/PayUCheckoutPro-Flutter#19]
Our app that used `payu_checkoutpro_flutter` was flagged by Google Play for violating the Device and Network Abuse policy due to a non-compliant version of the `Minkasu` SDK (com.minkasu:minkasu-2fa).

`payu_checkoutpro_flutter: ^1.0.4`

Email screenshot

<img width="824" alt="Screenshot 2024-04-19 at 12 31 31 PM" src="https://github.com/payu-intrepos/PayUCheckoutPro-Flutter/assets/56157868/fb27ffda-47bd-4ed9-86bf-8f3ea6a9a5ee">

**Comment by ShubhGar** [comment]
Hi @albinpk, we are working on same and will release with fix asap.

**Comment by shahfaizalc** [comment]
Kindly update to the latest version released. The issue has been addressed.
Thanks for reaching out to us.
Show quoted text

**Comment by shahfaizalc** [comment]
payu_checkoutpro_flutter: ^1.1.3

**Comment by albinpkChavara** [comment]
Has the `minimum deployment target` for iOS changed to `13.0`? @shahfaizalc

**Comment by albinpk** [comment]
Has the `minimum deployment target` for iOS changed to `13.0`? @shahfaizalc
