### ISSUE TITLE
Loader keeps loading

### ISSUE THREAD

**Issue by san-sitesurface** [payu-intrepos/PayUCheckoutPro-Flutter#2]
Getting please wait loader continuously nothing happens payu_checkoutpro_flutter: ^1.0.0 . Also not getting any error logs.

**Comment by secanonm** [comment]
same issue

**Comment by chrisbinsunny** [comment]
Did you find a solution? @secanonm @san-sitesurface

**Comment by umangarya336** [comment]
@san-sitesurface @secanonm @chrisbinsunny Please share steps to repro and screenshot to [mobile.integration@payu.in](mailto:mobile.integration@payu.in)

**Comment by secanonm** [comment]
> @san-sitesurface @secanonm @chrisbinsunny Please share steps to repro and screenshot to [mobile.integration@payu.in](mailto:mobile.integration@payu.in)

just copy your example and debug it 

its never be load payment page 

Logs :
Flutter : 3.3.5
payu_checkoutpro_flutter: 1.0.0
Android Version : 11

**Comment by secanonm** [comment]
![Screenshot_2022-11-02-10-53-30-922_com scupper](https://user-images.githubusercontent.com/54258853/199560881-fcf7a08c-c57f-4531-b049-d39a35349712.jpg)

**Comment by chrisbinsunny** [comment]
> @san-sitesurface @secanonm @chrisbinsunny Please share steps to repro and screenshot to [mobile.integration@payu.in](mailto:mobile.integration@payu.in)

@umangarya336 I tried the same code from the example app.
The same parameters when passed in Postman, shows a webpage saying "Redirecting to a new page". When passed on the app it shows nothing but a spinning loader. No error logs are being shown also. Even though it showed an error when I used the wrong hash.

I tested by setting the environment to test.

**Comment by secanonm** [comment]
I will fixed it for payu if you @umangarya336 guys ready ??

**Comment by rajansh09** [comment]
@chrisbinsunny, @secanonm , @san-sitesurface 

Kindly add the HashService class to your project. Inside the HashService class, you need to set your salt value on this variable "merchantSalt".

Add the below line of code inside the generateHash() method :- 
  @override
  generateHash(Map response) {
    // Pass response param to your backend server
    // Backend will generate the hash which you need to pass to SDK
    // hashResponse: is the response which you get from your server
    Map hashResponse = HashService.generateHash(response);
    _checkoutPro.hashGenerated(hash: hashResponse);
  }

**PFA :- HashService.dart class**

//Add _flutter pub add crypto_ plugin to use following class in your app. 
//Remove this plugin when you implement the salt at your server..

import 'package:crypto/crypto.dart';
import 'dart:convert';

class HashService {

static const merchantSalt = "1b1b0";//TODO: Add Salt 
static const merchantSecretKey = "";//TODO: Add Merchant Secrete Key - Optional

  static Map generateHash(Map response) {

    
    var hashName = response[PayUHashConstantsKeys.hashName];
    var hashStringWithoutSalt = response[PayUHashConstantsKeys.hashString];
    var hashType = response[PayUHashConstantsKeys.hashType];
    var postSalt = response[PayUHashConstantsKeys.postSalt];

    var hash = "";

    if (hashType == PayUHashConstantsKeys.hashVersionV2) {
      hash = getHmacSHA256Hash(hashStringWithoutSalt, merchantSalt);
    } else if (hashName == PayUHashConstantsKeys.mcpLookup) {
      hash = getHmacSHA1Hash(hashStringWithoutSalt, merchantSecretKey);
    } else {
      var hashDataWithSalt = hashStringWithoutSalt + merchantSalt;
      if (postSalt != null) {
        hashDataWithSalt = hashDataWithSalt + postSalt;
      }
      hash = getSHA512Hash(hashDataWithSalt);
    }
    //Don't use this method, get the hash from your backend.
    var finalHash = {hashName: hash};
    return finalHash;
  }

  //Don't use this method get the hash from your backend.
  static String getSHA512Hash(String hashData) {
    var bytes = utf8.encode(hashData); // data being hashed
    var hash = sha512.convert(bytes);
    return hash.toString();
  }

  //Don't use this method get the hash from your backend.
  static String getHmacSHA256Hash(String hashData, String salt) {
    var key = utf8.encode(salt);
    var bytes = utf8.encode(hashData);
    final hmacSha256 = Hmac(sha256, key)
      .convert(bytes)
      .bytes;
    final hmacBase64 = base64Encode(hmacSha256);
    return hmacBase64;
  }

  static String getHmacSHA1Hash(String hashData, String salt) {
    var key = utf8.encode(salt);
    var bytes = utf8.encode(hashData);
    var hmacSha1 = Hmac(sha1, key); // HMAC-SHA1
    var hash = hmacSha1.convert(bytes);
    return hash.toString();
  }
}

Note:- For static hash generation purposes, you should need to use the HashService class. Once you can move to production then you should need to create the dynamic hashes from the server. Inside the generate hash already written the steps.
  // Pass response param to your backend server
  // Backend will generate the hash which you need to pass to SDK
  // hashResponse: is the response which you get from your server
 // To generate local Hash use following code in your app, 

[2:07 pm] Rishabh Jaiswal
Kindly add the HashService class to your project. Inside the HashService class, you need to set your salt value on this variable "merchantSalt".
PFA :- HashService.dart class
Add the below line of code inside the generateHash() method :- 
  @override
  generateHash(Map response) {
    // Pass response param to your backend server
    // Backend will generate the hash which you need to pass to SDK
    // hashResponse: is the response which you get from your server
    Map hashResponse = HashService.generateHash(response);
    _checkoutPro.hashGenerated(hash: hashResponse);
  }
Note:- For static hash generation purposes, you should need to use the HashService class. Once you can move to production then you should need to create the dynamic hashes from the server. Inside the generate hash already written the steps.
  // Pass response param to your backend server
    // Backend will generate the hash which you need to pass to SDK
    // hashResponse: is the response which you get from your server

Please feel free to reach out if you have any questions to <mobile.integration@payu.in>

**Comment by secanonm** [comment]
Why you make this so complicated for beginners, 
You can predefined all class in your package so it takes less time to configure

**Comment by secanonm** [comment]
It's better we use unofficial package who provide better support

**Comment by chrisbinsunny** [comment]
@rajansh09 @umangarya336 I get the payment screen when using the test HashService class. But the thing is, I already have a hash returned from the backend server. How to use this hash in the app? Can you provide some example code for production apps? I really need this to complete the project.

**Comment by rajansh09** [comment]
@chrisbinsunny Use following delegate method and pass your hash generate in backend.  Call _checkoutPro.hashGenerated(hash: hashResponse),  method of checkout pro to pass your hash back to SDK. 

@override   generateHash(Map response) {    
 	// Pass response param to your backend server     
	// Backend will generate the hash which you need to pass to SDK    
 	// hashResponse: is the response which you get from your server    
	 Map hashResponse = {<commandName>:<Hash>};     	
	_checkoutPro.hashGenerated(hash: hashResponse);   
}

Please feel free to reach out if you have any questions to mobile.integration@payu.in

**Comment by rajansh08** [comment]
Local hash service added in the sample app for testing only. Don't use it for production.

**Comment by aarvyhimanshu01** [comment]
Hi! my screen is also stuck on please wait message!
The `generateHash(Map response)` method is called 3 times when `checkoutPro.openCheckoutScreen` is being called, and all of the 3 times the response is different hashNames `hashName: get_sdk_configuration`, `hashName: payment_related_details_for_mobile_sdk`, `hashName: signature, hashType: V2` .

which hash should be generated on backend? and even if I use all hashes `hashGenerated()` function it is still stuck on loading screen.

I have also tried this locally(used your eg. code), the hashes are same as from the backend, but result is still the same. I do not know what is going wrong here.

**Comment by secanonm** [comment]
not work with PHP dynamic hash still stuck on the loading page 
my hash 

```
 {
payment_hash: d2477d29f674bb3f01ffc01a384a31105699a867e75c22af1a.........., 
get_merchant_ibibo_codes_hash: 1dc4618d0546295cc5830dff8adeeeb9626......,
vas_for_mobile_sdk_hash: 3c6755e5c4779b94cef.....,
emi_hash: 8fde98b3e38996261e5920941caa16fed9e6cfc1390bb9ff75fc4a.......,
payment_related_details_for_mobile_sdk_hash: 8ce23914ef0a499a4fcc5aa201da8b1790a49c8f8b76e2......, verify_payment_hash: cb7484701fd47d470c328b2ed3c20......,
send_sms_hash: 0609032e904b6b540617b3521546.........
}
```

**Comment by sidhu-patil** [comment]
```PHP
<?PHP

$output = HashService::generateHash($_POST['hash']); // pass your response map here
echo header('content-type: application/json');
echo json_encode($output);

class HashService {
  const merchantSalt = ""; // Add your merchantSalt here
  const merchantSecretKey = ""; //optional 

  public static function generateHash($response) {
    $hashName = $response["hashName"];
    $hashStringWithoutSalt = $response["hashString"];
    $hashType = $response["hashType"] ?? null;
    $postSalt = $response["postSalt"] ?? null;

    $hash = "";

    if ($hashType == "V2") {
      $hash = self::getHmacSHA256Hash($hashStringWithoutSalt, self::merchantSalt);
    } else if ($hashName == "mcpLookup") {
      $hash = self::getHmacSHA1Hash($hashStringWithoutSalt, self::merchantSecretKey);
    } else {
      $hashDataWithSalt = $hashStringWithoutSalt . self::merchantSalt;
      if ($postSalt != null) {
        $hashDataWithSalt = $hashDataWithSalt . $postSalt;
      }
      $hash = self::getSHA512Hash($hashDataWithSalt);
    }
    $finalHash = [$hashName => $hash];
    return $finalHash;
  }

  public static function getSHA512Hash($hashData) {
    $bytes = utf8_encode($hashData); // data being hashed
    $hash = hash("sha512", $bytes);
    return $hash;
  }

  public static function getHmacSHA256Hash($hashData, $salt) {
    $key = utf8_encode($salt);
    $bytes = utf8_encode($hashData);
    $hmacSha256 = hash_hmac("sha256", $bytes, $key);
    $hmacBase64 = base64_encode($hmacSha256);
    return $hmacBase64;
  }

  public static function getHmacSHA1Hash($hashData, $salt) {
    $key = utf8_encode($salt);
    $bytes = utf8_encode($hashData);
    $hmacSha1 = hash_hmac("sha1", $bytes, $key); // HMAC-SHA1
    $hash = $hmacSha1;
    return $hash;
  }
}

?>

```



please add this code to your flutter pub documentation 

Thank You

**Comment by chrisbinsunny** [comment]
> Hi! my screen is also stuck on please wait message! The `generateHash(Map response)` method is called 3 times when `checkoutPro.openCheckoutScreen` is being called, and all of the 3 times the response is different hashNames `hashName: get_sdk_configuration`, `hashName: payment_related_details_for_mobile_sdk`, `hashName: signature, hashType: V2` .
> 
> which hash should be generated on backend? and even if I use all hashes `hashGenerated()` function it is still stuck on loading screen.
> 
> I have also tried this locally(used your eg. code), the hashes are same as from the backend, but result is still the same. I do not know what is going wrong here.

I am also facing the same issue. I get payment page while using ```HashService.generateHash(response)```, but the hash is not same even if the passed parameters are same. Hash works in Postman. 
And as @aarvyhimanshu01 said, generateHash(Map response) method is called many times and is returning different responses and hashNames. 
I am really confused here. It'll be so much better if can show a full code example.

**Comment by ravitejaavv** [comment]
@chrisbinsunny generateHash is getting called 3 times.. 

Do we have to call server for 3 hashes and set  _checkoutPro.hashGenerated(hash: hashResponse) ?

@rajansh09 I request you to clarify this

**Comment by sidhu-patil** [comment]
Here is a comprehensive guide on how to seamlessly integrate PayU's payment gateway into your Flutter app, which you can explore and benefit from: https://sudhanshupatil.medium.com/integrating-payu-payment-gateway-in-your-flutter-app-c3849433b32e

**Comment by manujjagga421** [comment]
@ravitejaavv @chrisbinsunny @sidhu-patil   were you able to fix this? Facing same issue. was using native android earlier and we have a backend service in place to generate hash but that returns string instead of a object that is expected in _checkoutPro.hashGenerated method. generate hash method is getting called twice and on second instance it is returning invalid hash. working perfectly on native android.

**Comment by sidhu-patil** [comment]
https://sudhanshupatil.medium.com/integrating-payu-payment-gateway-in-your-flutter-app-c3849433b32e


You can read this article

**Comment by manujjagga421** [comment]
@sidhu-patil  followed everything but getting {errorCode: 5019, errorMsg: Invalid Hash.} for payment_related_details_for_mobile_sdk

**Comment by manujjagga421** [comment]
@sidhu-patil  also generateHash is getting called multiple times does that mean i'll have to generate multiple hashes?

**Comment by sidhu-patil** [comment]
can you please share your code/ github repo link
