### ISSUE TITLE
Incompatible with Flutter `v3.22.0`

### ISSUE THREAD

**Issue by albinpk** [payu-intrepos/PayUCheckoutPro-Flutter#21]
The `payu_checkoutpro_flutter` package is not supported on the latest Flutter version `3.22.0`

### Version

- payu_checkoutpro_flutter: 1.1.4
- Flutter 3.22.0
- Dart 3.4.0

### Error

```
The current Dart SDK version is 3.4.0.

Because payu_checkoutpro_flutter 1.1.4 requires SDK version >=2.17.5 <=3.3.4 and no versions of
  payu_checkoutpro_flutter match >1.1.4 <2.0.0, payu_checkoutpro_flutter ^1.1.4 is forbidden.
So, because my_app depends on payu_checkoutpro_flutter ^1.1.4, version solving failed.
```

**Comment by albinpk** [comment]
Any updates on this?

**Comment by ravipiplani** [comment]
Any update on this?

**Comment by ravipiplani** [comment]
@umangarya336 @rajansh09 please update

**Comment by shahfaizalc** [comment]
We are working on the release will update the release verion soon and let you know.

**Comment by ravipiplani** [comment]
hi @shahfaizalc any update on this would help. We are stuck on older version because of PayU sdk only!

**Comment by shahfaizalc** [comment]
hi ravi, kindly drop a mail to  mobile.integration@payu.in. Our team will reach out to you

**Comment by rajansh09** [comment]
@ravipiplani Shah Faizal will connect with you tomorrow or setup a call with us.

**Comment by nimesh-devloper** [comment]
hyy 

is there any update ?

when is this library going to support the latest Flutter project?

**Comment by pratikvarsani013** [comment]
hi @shahfaizalc any update on this would help. 
We are stuck on older version because of PayU SDK only

**Comment by shahfaizalc** [comment]
The current Dart SDK version is 3.4.0.- we are releasing the updated version by monday.. with the latest dart support. the version will be **1.2.0**

**Comment by akashkamble012** [comment]
> The current Dart SDK version is 3.4.0.- we are releasing the updated version by monday.. with the latest dart support. the version will be **1.2.0**

Any Update? We are waiting for this.

**Comment by nimesh-devloper** [comment]
hyy 

is there any updates regarding the latest flutter version ????

**Comment by shahfaizalc** [comment]
@ravipiplani @pratikvarsani013 @akashkamble012 @albinpk  kindly use the latest version https://pub.dev/packages/payu_checkoutpro_flutter

**Comment by shahfaizalc** [comment]
@nimesh-devloper kindly use the latest version https://pub.dev/packages/payu_checkoutpro_flutter
