### ISSUE TITLE
errorMsg: Invalid Hash.

### ISSUE THREAD

**Issue by nitesharma** [payu-intrepos/PayUCheckoutPro-Flutter#22]
I am getting an error invalid hash using both the test and production environment. I also tried using both methods to create a hash on the server or in a dart file. But the issue remains the same.

flutter: {"get_sdk_configuration":"cf492660304901b6fc17f918ba63b81ffbc97d4d1243981d29e719bde7df68cd752480838a31ef611ba15f05bf0079a3df5ba6c0de6e81855d14284e51c4a6c5"}
flutter: {"fetch_quick_pay_option":"98816c0105eb6e339338e6f2c82c72b06befee7aa34941e97775dbfd7c3fb0333fc8b40609c301fee0e6546596f9b30aec2701116f7477448fe7a862009c583f"}
flutter: {"payment_related_details_for_mobile_sdk":"481647886a56cb93487acd063d9a87039680c7994da3542ab873049f7f95b4d235eda19aba2a210ed29b89e9bdef32290a1cf61c46182849a162f0865f1c6ef5"}
flutter: {"get_checkout_details":"a77d992f1eced725be45373bbf6d572e7a93f4f0a3d56e26beaadb812d42c1349d3456160309a84240aee0bf9db114fb81884a6a0feab4d4a5d0ece475f99417"}
[log] {errorMsg: Invalid Hash.}

**Comment by ShubhGar** [comment]
Please connect with [mobile.integration@payu.in](mailto:mobile.integration@payu.in) they will help you.
