### ISSUE TITLE
Asset validation failed (90482) Invalid Executable. The executable 'Runner.app/Frameworks/PayUAnalytics.framework/PayUAnalytics' contains bitcode. (ID: 20871d97-f50a-4bae-a0c3-d8d74f9ed6a7)+

### ISSUE THREAD

**Issue by Gurjap** [payu-intrepos/PayUCheckoutPro-Flutter#23]
in Xcode 16 I am not able to upload app to appstore. this issue is coming up.

**Comment by ShubhGar** [comment]
Hi @Gurjap  ,
We will release new version of flutter in somedays. Please connect with [mobile.integration@payu.in](mailto:mobile.integration@payu.in) they will suggest some work around to you.
