### ISSUE TITLE
Asset Validation Failed (Error 90482) Due to Bitcode in PayUAnalytics Framework

### ISSUE THREAD

**Issue by nishantvekariya21** [payu-intrepos/PayUCheckoutPro-Flutter#24]
**Description**: I am encountering an issue when validating my app for submission to the App Store. The validation fails with the following error:

`Asset validation failed (90482)
Invalid Executable. The executable 'Runner.app/Frameworks/PayUAnalytics.framework/PayUAnalytics' contains bitcode. (ID: 3d793dc9-dce0-43ff-b5c3-94943fd89750)
`

**Environment**:
- Xcode Version: [Your Xcode version, e.g., 16.0]
- macOS Version: [Your macOS version, e.g., macOS 14.0]
- Flutter Version: [Your Flutter version, e.g., 3.7.0]
- PayUAnalytics Version: [The version of the PayUAnalytics framework you are using]

**Steps to Reproduce**:
1. Create a Flutter project and integrate the PayUAnalytics framework.
2. Build the project for iOS.
3. Archive the app in Xcode.
4. Validate the archive for submission to the App Store.

**Expected Behavior**:
The app should validate successfully without any errors related to bitcode.

**Actual Behavior**:
The validation process fails with the error mentioned above, indicating that the PayUAnalytics framework contains bitcode, which is not allowed in the current App Store submission process.

**Attempts to Fix**:
I have tried disabling bitcode in my Podfile as follows:

```
post_install do |installer|
     installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
               config.build_settings['ENABLE_BITCODE'] = 'NO'
               config.build_settings['BITCODE_GENERATION_MODE'] = 'marker'
          end
     end
end
```

However, the error persists, indicating that the PayUAnalytics framework still contains bitcode.

**Additional Information**:
If the PayUAnalytics framework needs to be rebuilt without bitcode, please provide guidance or any updates regarding a version that addresses this issue.

Thank you!

**Comment by ShubhGar** [comment]
Hi @nishantvekariya21 ,
We will release new version of flutter in somedays. Please connect with mobile.integration@payu.in they will suggest some work around to you.
