### ISSUE TITLE
stuck on payumoney logo 

### ISSUE THREAD

**Issue by Abhaysharma652** [payu-intrepos/PayUCheckoutPro-Flutter#25]
try use payumoney on flutter clone but code is not working and also when upgrade its navigate to payumoney logo and app are stuck tere add surl furl and merchant key everything those i am working on android code but in flutter its not working

**Comment by shahfaizalc** [comment]
kindly reach out to  mobile.integration@payu.in

**Comment by bashu-riyan** [comment]
whats the solution
