### ISSUE TITLE
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject 

### ISSUE THREAD

**Issue by shreyasSarve** [payu-intrepos/PayUCheckoutPro-Flutter#4]
example app is giving this error any help please

**Comment by Velmurugan-404** [comment]
Do have the answer, why that error appears? Please let me know.

**Comment by shahfaizalc** [comment]
@Velmurugan-404  @shreyasSarve  please reach us at  <mobile.integration@payu.in> we will help you on resolving this issue.

**Comment by sage237** [comment]
This error occurs when changing salt and key, 
if anyone has solution please help

**Comment by AjnasAskar** [comment]
It occurs when we use test key for production or vice versa

**Comment by sramac2** [comment]
Steps I followed to resolve that issue:
1. Check that you set the salt on the HashService class. Variable name: **merchantSalt**
2. On the main file, set **merchantKey** to the merchant key you were provided with
3. Set the IoS and android URLS with whatever is appropriate. **Surl** means success URL. Not sure why they would use such acronyms, its very confusing. 
4. Set **PayUPaymentParamKey.environment:** to 1 if you are still in testing mode. //0 => Production 1 => Test

**Comment by sidhu-patil** [comment]
Here is a comprehensive guide on how to seamlessly integrate PayU's payment gateway into your Flutter app, which you can explore and benefit from: https://sudhanshupatil.medium.com/integrating-payu-payment-gateway-in-your-flutter-app-c3849433b32e

**Comment by shahfaizalc** [comment]
kindly use the latest version https://pub.dev/packages/payu_checkoutpro_flutter
