### ISSUE TITLE
App crash when click on offer icon

### ISSUE THREAD

**Issue by sidhu-patil** [payu-intrepos/PayUCheckoutPro-Flutter#6]
Payu Package Version: 1.0.1
Android  Version: 11

Logs:-

D/DecorView(13235): createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
D/AndroidRuntime(13235): Shutting down VM
E/AndroidRuntime(13235): FATAL EXCEPTION: main
E/AndroidRuntime(13235): Process: com.scupper, PID: 13235
E/AndroidRuntime(13235): java.lang.NullPointerException
E/AndroidRuntime(13235): 	at com.payu.ui.view.activities.CheckoutActivity.c(SourceFile:271)
E/AndroidRuntime(13235): 	at com.payu.ui.view.activities.CheckoutActivity.h(SourceFile:1)
E/AndroidRuntime(13235): 	at com.payu.ui.view.activities.CheckoutActivity$$ExternalSyntheticLambda26.onChanged(Unknown Source:4)
E/AndroidRuntime(13235): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
E/AndroidRuntime(13235): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
E/AndroidRuntime(13235): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
E/AndroidRuntime(13235): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
E/AndroidRuntime(13235): 	at com.payu.ui.view.activities.CheckoutActivity.a(SourceFile:280)
E/AndroidRuntime(13235): 	at com.payu.ui.model.widgets.a.onViewCreated(SourceFile:2)
E/AndroidRuntime(13235): 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
E/AndroidRuntime(13235): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
E/AndroidRuntime(13235): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
E/AndroidRuntime(13235): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
E/AndroidRuntime(13235): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
E/AndroidRuntime(13235): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
E/AndroidRuntime(13235): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
E/AndroidRuntime(13235): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(13235): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13235): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(13235): 	at android.app.ActivityThread.main(ActivityThread.java:7904)
E/AndroidRuntime(13235): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13235): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(13235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by shahfaizalc** [comment]
kindly connect to us at mobile.integration@payu.in. will help you on this

**Comment by Keshav-Kishor-143** [comment]
@shahfaizalc I am trying to integrate payU in my flutter project. I have imported the sdk and the plugin and I am using the repository code. 
I am getting Invalid hash code as the error while hitting the select  payment button. 
I am using test credentials(name, number, email,, etc) with merchant key and salt. 
I am not getting hash from backend, but sticking to the code itself. Please suggest an idea to check if the hash code is required prior to initiating payment or after that.
