### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "com.payu.phonepe.PhonePeWrapper"  Getx Flutter

### ISSUE THREAD

**Issue by iamrajdev** [payu-intrepos/PayUCheckoutPro-Flutter#7]
java.lang.ClassNotFoundException: Didn't find class "com.payu.phonepe.PhonePeWrapper" on path: DexPathList[[zip file "/data/app/com.sapcoiot.carsewa-ce8qG7z3XT4jXSbs-hlrEg==/base.apk"],nativeLibraryDirectories=[/data/app/com.sapcoiot.carsewa-ce8qG7z3XT4jXSbs-hlrEg==/lib/arm64, /data/app/com.sapcoiot.carsewa-ce8qG7z3XT4jXSbs-hlrEg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]

Flutter getx
android app crash!
buildtool version: 33
Android API: 31

Any Solution ??

**Comment by shahfaizalc** [comment]
kindly write us at [mobile.integration@payu.in](mailto:mobile.integration@payu.in) . We will help you on resolving this issue.

**Comment by imrajdev** [comment]
Solved.

**Comment by shridhar9** [comment]
> Solved.

How did you solved it?
