### ISSUE TITLE
not working in ios

### ISSUE THREAD

**Issue by nbpatel94** [payu-intrepos/PayUCheckoutPro-Flutter#8]
hello 

onError method call when click openCheckoutScreen.  {errorMsg: Error in decoding payment response}  in ios.

Can you please test and give me solutions for this because i already try to find solution for this but can't find it.

**Comment by tanishqarora97** [comment]
> hello 
> 
> onError method call when click openCheckoutScreen.  {errorMsg: Error in decoding payment response}  in ios.
> 
> Can you please test and give me solutions for this because i already try to find solution for this but can't find it.

Any solution

**Comment by AmitPayU** [comment]
@nbpatel94 @tanishqarora97, Please reach us at [mobile.integration@payu.in]

**Comment by kesamani** [comment]
can you get any solution i also facing same issue

**Comment by tanishqarora97** [comment]
> can you get any solution i also facing same issue
Downgrade to lower version resolved the issue for me.

**Comment by AmitPayU** [comment]
Please reach us at mobile.integration@payu.in

**Comment by kesamani** [comment]
Downgrade to lower version resolved the issue for me.
its now working for me ,facing the same issue  which version is working for you.

**Comment by Amit-wct** [comment]
When I tried in ios it gives error as payment parameters are not same but the same works in android

**Comment by gada-raj** [comment]
> When I tried in ios it gives error as payment parameters are not same but the same works in android

Check The length of the Transaction Id IOS only supports upto 25 charcters

**Comment by ShubhGar** [comment]
Please connect with [mobile.integration@payu.in](mailto:mobile.integration@payu.in) they will help you.
